# Generated by Django 3.0.3 on 2020-04-12 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20200413_0003'),
        ('useroperate', '0002_auto_20200409_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favor_article',
            options={'verbose_name': '文章收藏记录', 'verbose_name_plural': '文章收藏记录'},
        ),
        migrations.AlterField(
            model_name='favor_article',
            name='articles',
            field=models.ForeignKey(help_text='文章id', on_delete=django.db.models.deletion.CASCADE, related_name='favors_a', to='blogs.Article', verbose_name='收藏的文章'),
        ),
    ]
