# Generated by Django 3.0.3 on 2020-04-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='birth_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_dsc',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_state',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(blank=True, default='20200409170425484622', max_length=20, verbose_name='昵称'),
        ),
    ]
