# Generated by Django 3.0.3 on 2020-04-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200409_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': '用户管理', 'verbose_name_plural': '用户管理'},
        ),
        migrations.AlterModelOptions(
            name='verifycode',
            options={'verbose_name': '邮件验证码管理', 'verbose_name_plural': '邮件验证码管理'},
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='avatar',
            field=models.ImageField(default='avatars/default_avatar.png', help_text='用户头像', upload_to='avatars/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='birth_date',
            field=models.DateTimeField(help_text='出生日期', null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(blank=True, default='20200413000334273043', help_text='昵称', max_length=20, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_dsc',
            field=models.TextField(help_text='个人描述', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_state',
            field=models.CharField(help_text='用户状态', max_length=4, null=True),
        ),
    ]
